In [3]:
 import numpy as np

In [5]:
arr=np.array([1,2,3,4,5,6])
arr

array([1, 2, 3, 4, 5, 6])

In [6]:
list_of_lists=[[1,2,3],[4,5,6],[7,8,9]]
sample_matrix=np.array(list_of_lists)

In [6]:
sample_matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [8]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
np.arange(19)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18])

In [10]:
np.arange(1,46,5)

array([ 1,  6, 11, 16, 21, 26, 31, 36, 41])

In [11]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [12]:
np.zeros(5,int)

array([0, 0, 0, 0, 0])

In [13]:
np.zeros(10,dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [14]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [15]:
np.ones(100,int)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [16]:
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [18]:
np.linspace(0,20,8)

array([ 0.        ,  2.85714286,  5.71428571,  8.57142857, 11.42857143,
       14.28571429, 17.14285714, 20.        ])

In [19]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [20]:
np.random.rand(3,2)

array([[0.88902153, 0.26461247],
       [0.17346778, 0.25422549],
       [0.23469599, 0.8856335 ]])

In [21]:
np.random.randn(34,100)

array([[-0.8113413 ,  0.17591203,  0.3868921 , ...,  0.58361187,
        -0.3193719 ,  0.32990105],
       [-1.35096088,  0.11988729,  0.70822386, ...,  0.36419163,
        -1.42285475,  0.96881939],
       [ 0.89867822,  0.24867668,  1.3180205 , ...,  0.9807699 ,
        -0.6811464 , -0.4777967 ],
       ...,
       [-1.02306885,  1.47943761, -0.3680176 , ...,  2.52292275,
         0.73904211,  0.5887975 ],
       [ 0.93191469,  0.45669453,  0.05270013, ..., -0.39563591,
        -0.64375568, -1.15709161],
       [-1.03312073,  0.06921816, -1.10197268, ..., -1.27687815,
        -0.56139814, -0.73097915]])

In [22]:
np.random.randint(34,100,50)

array([39, 76, 71, 70, 52, 54, 89, 66, 45, 40, 78, 69, 66, 52, 71, 51, 67,
       80, 37, 70, 97, 75, 72, 88, 89, 41, 45, 48, 83, 34, 78, 68, 66, 93,
       96, 97, 94, 92, 70, 49, 93, 91, 86, 48, 65, 52, 41, 87, 56, 37])

In [4]:
sample_array=np.arange(30)
sample_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [11]:
rand_array=np.random.randint(0,100,20)
rand_array

array([ 0, 21, 22, 27, 12, 89,  1, 44, 56, 24, 91,  4, 37, 29,  1, 66, 95,
       61,  2,  0])

In [8]:
sample_array.reshape(5,6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [12]:
rand_array.min()

0

In [13]:
rand_array.argmin()

0

In [14]:
sample_array.dtype

dtype('int32')

In [17]:
a=np.eye(5)
a

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [18]:
a.T

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [19]:
a=np.random.rand(2,3)
a

array([[0.91997915, 0.27516262, 0.15961857],
       [0.78389821, 0.45696495, 0.13778277]])

In [20]:
a.T

array([[0.91997915, 0.78389821],
       [0.27516262, 0.45696495],
       [0.15961857, 0.13778277]])

In [21]:
sapmle_array=np.arange(10,21)
sample_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [22]:
sample_array[3]

3

In [23]:
sample_array[3:7]

array([3, 4, 5, 6])

In [24]:
sample_array[1:4]=100
sample_array

array([  0, 100, 100, 100,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29])

In [29]:
sample_array[10:21]
sample_array

array([   0, 1001, 1001, 1001,    4,    5,    6,    7,    8,    9,  100,
        100,  100,  100,  100,  100,  100,  100,  100,  100,  100,   21,
         22,   23,   24,   25,   26,   27,   28,   29])

In [30]:
sample_array[0:7]

array([   0, 1001, 1001, 1001,    4,    5,    6])

In [31]:
subset_sample_array=sample_array[0:7]
subset_sample_array

array([   0, 1001, 1001, 1001,    4,    5,    6])

In [32]:
subset_sample_array[1:4]=1001
subset_sample_array

array([   0, 1001, 1001, 1001,    4,    5,    6])

In [33]:
subset_sample_array[:]=1001
subset_sample_array

array([1001, 1001, 1001, 1001, 1001, 1001, 1001])